import pandas as pd

category_list = [
    ['COMPUTER SCIENCE AND ENGINEERING', 'COMPUTER SCIENCE AND ENGINEERING (SS)'],
    ['INFORMATION TECHNOLOGY', 'INFORMATION TECHNOLOGY (SS)', 'INFORMATION SCIENCE AND ENGINEERING'],
    ['COMPUTER SCIENCE AND BUSINESS SYSTEM', 'COMPUTER SCIENCE AND BUSINESS SYSTEM (SS)'],
    ['COMPUTER SCIENCE AND ENGINEERING(ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING)', 'COMPUTER SCIENCE AND ENGINEERING(ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING) (ss)'],
    ['ARTIFICIAL INTELLIGENCE AND DATA SCIENCE', 'ARTIFICIAL INTELLIGENCE AND DATA SCIENCE(SS)'],
    ['CIVIL ENGINEERING', 'CIVIL ENGINEERING(SS)'],
    ['ELECTRONICS AND COMMUNICATION ENGINEERING', 'ELECTRONICS AND COMMUNICATION ENGINEERING (SS)'],
    ['ELECTRICAL AND ELECTRONICS ENGINEERING', 'ELECTRICAL AND ELECTRONICS ENGINEERING (SS)', 'ELECTRICAL AND ELECTRONICS ENGINEERING (SANDWICH) (SS)'],
    ['MECHANICAL ENGINEERING', 'MECHANICAL ENGINEERING (SS)', 'MECHANICAL ENGINEERING (SANDWICH) (SS)'],
    ['MECHATRONICS ENGINEERING', 'MECHATRONICS (SS)'],
    ['ROBOTICS AND AUTOMATION', 'ROBOTICS AND AUTOMATION (SS)'],
    ['METALLURGICAL ENGINEERING', 'METALLURGICAL ENGINEERING (SS)'],
    ['PRODUCTION ENGINEERING', 'PRODUCTION ENGINEERING (SS)', 'PRODUCTION ENGINEERING (SANDWICH)(SS)'],
    ['FOOD TECHNOLOGY', 'FOOD TECHNOLOGY(SS)'],
    ['BIO TECHNOLOGY', 'BIO TECHNOLOGY (SS)', 'INDUSTRIAL BIO TECHNOLOGY', 'INDUSTRIAL BIO TECHNOLOGY (SS)']
]

def category(course):
    for category in category_list:
        if course in category:
            return category
    return [course]

def list_of_colleges(mark, course, community, data):
    course_final = category(course)
    filtered_data = data[data['Branch Name'].isin(course_final) & (data[community] <= (mark + 5))]
    result = filtered_data[['College Code', 'College Name', 'Branch Name', 'Branch Code', community]]
    result = result.sort_values(by=community, ascending=False)
    return result


#check commit 